language: python
sudo: false
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=lint
  - python: "2.7"
    env: TOX_ENV=py27-oauth2client1
  - python: "2.7"
    env: TOX_ENV=py27-oauth2client2
  - python: "2.7"
    env: TOX_ENV=py27-oauth2client3
  - python: "2.7"
    env: TOX_ENV=py27-oauth2client4
  - python: "3.3"
    env: TOX_ENV=py33-oauth2client4
  - python: "3.4"
    env: TOX_ENV=py34-oauth2client4
  - python: "3.5"
    env: TOX_ENV=py35-oauth2client1
  - python: "3.5"
    env: TOX_ENV=py35-oauth2client2
  - python: "3.5"
    env: TOX_ENV=py35-oauth2client3
  - python: "3.5"
    env: TOX_ENV=py35-oauth2client4
install:
  # See https://github.com/aws/base64io-python/issues/4#issuecomment-397857642
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
  - pip install tox
  - pip install . argparse
script: tox -e $TOX_ENV
after_success:
  - if [[ "${TOX_ENV}" == "py27-oauth2client4" ]]; then tox -e coveralls; fi
